name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git user
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your_email@example.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        run: npm run deploy
