name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master # O main si tu rama principal es main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Usa la versión de Node.js que prefieras

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
